name = "tracktoss"
main = "_worker.js"
compatibility_date = "2024-03-28"

[site]
bucket = "./dist"
include = ["**/*"]
exclude = ["node_modules/**/*"]

[build]
command = "npm run build"

[[build.upload]]
format = "service-worker"

[build.upload.rules]
type = "ESModule"
fallthrough = true 